python3 C_Parser_new.py < test_programs/fseek.c
python3 C_Parser_new.py < test_programs/func_len.c
python3 C_Parser_new.py < test_programs/global_len_3.c
python3 C_Parser_new.py < test_programs/switch_case.c
python3 C_Parser_new.py < test_programs/test_while.c
python3 C_Parser_new.py < test_programs/var_fsize.c
python3 C_Parser_new.py < test_programs/func_dec_size.c
python3 C_Parser_new.py < test_programs/gf.c
python3 C_Parser_new.py < test_programs/strcmp.c
python3 C_Parser_new.py < test_programs/uppercase.c
python3 C_Parser_new.py < test_programs/var_len.c
